[build]
pythonVersion = "3.11"

[environment]
TESSERACT_CMD_PATH = "/usr/bin/tesseract"

[deploy]
memory = 1024
disk = 1024
timeout = 300

[server]
maxUploadSize = 200

[ui]
hideSidebarNav = true
hideShareButton = true
hideManageAppButton = true
hideMenuButton = true
hideFooter = true
hideTopBar = true
hideToolbar = true
hideHeader = true
hideMainMenu = true
hideDevMenu = true
hideDeployButton = true

[client]
toolbarMode = "minimal"
