[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
enableCORS = false
maxUploadSize = 200
maxMessageSize = 50
headless = true

[logger]
level = "warning"
messageFormat = "%(asctime)s - %(levelname)s - %(message)s"

[cache]
ttl = 3600
maxEntries = 100
